###
GET http://localhost:8080/api/response-status-ex1
Accept: application/json

###
GET http://localhost:8080/api/response-status-ex2
Accept: application/json

###
GET http://localhost:8080/api/default-handler-ex?data=qq
Accept: application/json